### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by pavvelb** [mjefferys/tronplex#2]
Hi @mjefferys!

First of all thank you for your work! Finally proper Plex Player with the black window border!
Im using the Tronplex a couple of months and notice that wrapper sometimes dont open Plex just black window thats all!
Hope you fix this! Thank you!

**Comment by mjefferys** [comment]
Glad you're enjoying using it! When this happens do you get any window border at all, or just a pure black screen? I don't think i've ever had that happen, but I have some ideas I can put in place to try to mitigate.

**Comment by pavvelb** [comment]
Here is screenshot, this problem happen very offen
![2018-12-06](https://user-images.githubusercontent.com/39178626/49608828-c8000080-f9aa-11e8-9793-89db493481b9.png)

**Comment by mjefferys** [comment]
Interesting, I can't say it happens often to me. That being said, I've pushed a small update that will include a message while the plex app is attempting to load and how to ensure it does load on your next try. You should get the update automatically in a couple of minutes. If the app doesn't automatically update can you press 'f1' for me and give me the version your on?

I do have some thoughts for a more permanent fix, but I'll need some more time.

**Comment by pavvelb** [comment]
I recieve the update. Version now 1.0.110 Electron version 2.0.13

**Comment by mjefferys** [comment]
@pglionnexx  I think I should have fixed this in the latest release,

Can you grab version 1.0.122 and let me know if you see it again.

**Comment by pavvelb** [comment]
OK i will testing new version

**Comment by pavvelb** [comment]
@mjefferys After couple of run Tronplex i recieve message "Plex Load Failed, please press F5 to try again" on black screen.

**Comment by mjefferys** [comment]
Ok that's a good piece of data to have. 

As all I'm doing is trying to load https://app.plex.tv in the embedded browser at this point I would be inclined to suspect your system is having some issue connecting to Plex. 

What I can do is push a version that will automatically try to load Plex again any time it fails. As I assume that sometimes your machine loads Plex correctly? 

If so I'll push a version with that fix for you tomorrow.

**Comment by pavvelb** [comment]
Yes, i have some issues with remote access in Plex (in program i dont have green marker on remote access status) but it have
i have remote access from smartphone for example. Also i dont have trobles with access with Plex Media Player and UWP version of Plex Player.
Tronplex can run or dont, with disabled remote access in Plex

**Comment by mjefferys** [comment]
Tronplex by default should find your local servers assuming that it can contact plex.tv first. However, it does sound like your system sometimes has issues doing that. I can fall back to not contacting plex.tv and attempting to load a local install of plex if it fails. Are you running the Plex server on your local machine?

In the meantime, I've pushed a build that automatically retries on failure, version 1.0.126

**Comment by pavvelb** [comment]
Yes. i use Plex on local machine

**Comment by mjefferys** [comment]
Perfect, i've pushed v1.0.139 which should fall back to a local plex install if it can't find the main plex server. Let me know how you get on!

**Comment by pavvelb** [comment]
Alright, thanks for update i will test

**Comment by pavvelb** [comment]
Still have problems with connection to Plex. Both - local and remote Plex.  Then impossible to connect to remote server, trying to connect to local and failed.
